name: fe
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1

  flutter_chat_bubble: ^2.0.0
  url_launcher: ^6.0.18
  flutterfire_ui: ^0.3.0


  extended: ^0.1.5


  fireflutter:
    path: ..



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
