name: fireflutter
description: A free, open source, complete, rapid development package for creating Social apps, Chat apps, Community(Forum) apps, Shopping mall apps, and much more based on Firebase.
version: 0.2.7
homepage: https://github.com/thruthesky/fireflutter

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  firebase_database: ^9.0.4
  cloud_firestore: ^3.1.6

  rxdart: any

  
  # PhoneNumberInput widget
  country_code_picker: ^2.0.2

  # Chat room pagination
  paginate_firestore: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
